/**
 * 小游戏导航数据（Godot 旁路 + Web 互动）
 */

import type { GameItem } from '../types';

export const games: GameItem[] = [
  {
    id: 'pulse-parade',
    title: 'Pulse Parade',
    description: '节奏点按 MVP，校准与判定练习',
    path: '/games/pulse-parade/',
    tags: ['节奏', '点按', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-08-31',
    updatedAt: '2026-09-01',
  },
  {
    id: 'flappy-wish',
    title: '予愿飞翔',
    description: 'Flappy 风格竖版：三档难度、穿管/金币计分',
    path: '/games/flappy-wish/',
    tags: ['休闲', 'Flappy', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-07-30',
    updatedAt: '2026-09-01',
  },
  {
    id: 'suika-game',
    title: '合成大西瓜',
    description: '物理合成：投放色球碰撞合并，体积越大分越高',
    path: '/games/suika-game/',
    tags: ['物理', '合成', '休闲', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-04-25',
    updatedAt: '2026-09-01',
  },
  {
    id: 'bubble-shooter',
    title: '泡泡龙',
    description: '瞄准发射、同色连消与悬空掉落',
    path: '/games/bubble-shooter/',
    tags: ['泡泡龙', '连消', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-03-14',
    updatedAt: '2026-09-01',
  },
  {
    id: 'arknights-bubble-shooter',
    title: '岁家龙泡泡',
    description: '岁家五龙角色球：连消与悬空坠落',
    path: '/games/arknights-bubble-shooter/',
    tags: ['明日方舟', '泡泡龙', '岁家', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-04-25',
    updatedAt: '2026-09-01',
  },
  {
    id: 'miku-flick',
    title: 'Miku Flick',
    description: '假名键滑动方向判定与连击计分',
    path: '/games/miku-flick/',
    tags: ['节奏输入', 'MikuFlick', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-03-15',
    updatedAt: '2026-09-01',
  },
  {
    id: 'huarongdao-game',
    title: '图片华容道',
    description: '三关图片切块拼图、计时计分',
    path: '/games/huarongdao/',
    tags: ['华容道', '拼图', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-03-11',
    updatedAt: '2026-09-01',
  },
  {
    id: 'push-box',
    title: '推箱子',
    description: '50 关 Sokoban：选关、推箱、自动过关',
    path: '/games/push-box/',
    tags: ['推箱子', '益智', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-09-01',
    updatedAt: '2026-09-01',
  },
  {
    id: 'gold-miner',
    title: '黄金矿工',
    description: '12 关钩子采矿：抓金/石/钻，60 秒达目标分',
    path: '/games/gold-miner/',
    tags: ['黄金矿工', '休闲', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-09-01',
    updatedAt: '2026-09-01',
  },
  {
    id: 'miku-fusion-game',
    title: 'Miku Fusion',
    description: '加权投放、碰撞合并、连消倍率与最高分',
    path: '/games/miku-fusion-game/',
    tags: ['合成', '物理', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-02-16',
    updatedAt: '2026-09-01',
  },
  {
    id: 'link-game',
    title: '葱韵环京连连看',
    description: '六种模式、计时得分、提示与限次洗牌',
    path: '/games/link-game/',
    tags: ['连连看', '益智', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-09-01',
    updatedAt: '2026-09-01',
  },
  {
    id: 'race-game',
    title: '极速狂飙',
    description: '四车道躲避障碍、收集金币、加速与最高分',
    path: '/games/race-game/',
    tags: ['赛车', '街机', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-09-01',
    updatedAt: '2026-09-01',
  },
  {
    id: 'trible-game',
    title: '三消挑战',
    description: '四关尺寸/时限、连消倍率与最高分',
    path: '/games/trible-game/',
    tags: ['三消', '益智', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-09-01',
    updatedAt: '2026-09-01',
  },
  {
    id: 'miku-click',
    title: '米库点击',
    description: '限时点击连击与最高分',
    path: '/games/miku-click/',
    tags: ['点击', '休闲', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-09-01',
    updatedAt: '2026-09-01',
  },
  {
    id: 'kannot',
    title: '坎诺特',
    description: '四轨节奏、难度与最高分',
    path: '/games/kannot/',
    tags: ['节奏', '音乐', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-09-01',
    updatedAt: '2026-09-01',
  },
  {
    id: 'vocaloid-to-go',
    title: '博立格来冲',
    description: '假名词练习/挑战与准确率',
    path: '/games/vocaloid-to-go/',
    tags: ['词汇', '挑战', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-09-01',
    updatedAt: '2026-09-01',
  },
  {
    id: 'purchase-game',
    title: '谋财害命',
    description: '购买抉择、评级与最高分',
    path: '/games/purchase-game/',
    tags: ['策略', '抉择', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-09-01',
    updatedAt: '2026-09-01',
  },
  {
    id: 'mikutap-game',
    title: 'Mikutap Game',
    description: '自由点按与跟敲序列、最高分',
    path: '/games/mikutap-game/',
    tags: ['音乐', 'Mikutap', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2023-12-15',
    updatedAt: '2026-09-01',
  },
  {
    id: 'miku-planting',
    title: '米库种植',
    description: '限时收获目标与最高分',
    path: '/games/miku-planting/',
    tags: ['养成', '休闲', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-09-01',
    updatedAt: '2026-09-01',
  },
  {
    id: 'diner-dash',
    title: '罗德厨房',
    description: '明日方舟同人食堂班次：接待客人、上菜收桌',
    path: '/games/diner-dash/',
    tags: ['模拟经营', '明日方舟', 'Godot'],
    platform: 'godot',
    isCompleted: true,
    createdAt: '2026-08-29',
    updatedAt: '2026-09-01',
  },
  {
    id: 'miku-talking',
    title: '米库说话',
    description: 'MMD 互动：点击、语音变声、喂食与亲密度',
    path: '/gameField/mikutalking',
    tags: ['MMD', '互动', '3D', 'Web'],
    platform: 'web',
    isCompleted: false,
    createdAt: '2025-11-03',
    updatedAt: '2025-11-03',
  },
  {
    id: 'mikutap',
    title: 'Mikutap 音乐互动',
    description: '经典音乐互动：点击/拖拽触发音效与动画',
    path: '/testField/mikutap',
    tags: ['音乐', '互动', '初音未来', 'Web'],
    platform: 'web',
    isCompleted: true,
  },
  {
    id: 'playMusic',
    title: '音乐无料',
    description: '赛博无料音乐播放与互动',
    path: '/testField/playMusic',
    tags: ['音乐', '无料', 'Web'],
    platform: 'web',
    isCompleted: false,
  },
  {
    id: 'miku-fireworks-3d',
    title: 'Miku Fireworks 3D',
    description: '3D 烟花弹幕：普通/初音/头像烟花与实时弹幕',
    path: '/testField/mikuFireworks3D',
    tags: ['3D', '烟花', '弹幕', 'Web'],
    platform: 'web',
    isCompleted: true,
    createdAt: '2026-02-16',
    updatedAt: '2026-02-16',
  },
  {
    id: 'festival-card',
    title: '节日贺卡 Three.js',
    description: '3D 翻页节日贺卡，支持多页图文与背景音乐',
    path: '/testField/festivalCard',
    tags: ['Three.js', '贺卡', '3D', 'Web'],
    platform: 'web',
    isCompleted: true,
    createdAt: '2026-03-02',
    updatedAt: '2026-03-02',
  },
  {
    id: 'ticket-booking-mvp',
    title: '演出票务预定 MVP',
    description: '选演出、平面选座、订单确认与模拟支付',
    path: '/testField/TicketBooking',
    tags: ['票务', '选座', '演示', 'Web'],
    platform: 'web',
    isCompleted: true,
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'solar-system',
    title: '实时太阳系',
    description: '基于真实天文数据的太阳系 3D 可视化',
    path: '/testField/solarSystem',
    tags: ['天文', 'Three.js', '3D', 'Web'],
    platform: 'web',
    isCompleted: true,
  },
  {
    id: 'mmd-viewer',
    title: 'MMD 模型查看器',
    description: 'PMD/PMX 模型与 VMD 动画播放',
    path: '/testField/mmdViewer',
    tags: ['MMD', 'Three.js', '3D', 'Web'],
    platform: 'web',
    isCompleted: false,
  },
];
