#!/usr/bin/env python3
"""Filter nginx profile-platform.conf by runtime-modules.json.

Removes blocks delimited by:
  # @module <name>
  ...
  # @endmodule <name>

Usage:
  python3 render-runtime-nginx.py <modules.json> <full.conf> <out.conf>
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

BEGIN = re.compile(r"^\s*#\s*@module\s+(\S+)\s*$")
END = re.compile(r"^\s*#\s*@endmodule\s+(\S+)\s*$")


def enabled_set(path: Path) -> set[str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    return {
        k
        for k, v in data.items()
        if not str(k).startswith("_") and bool(v) is True
    }


def filter_conf(text: str, enabled: set[str]) -> str:
    out: list[str] = []
    skipping: str | None = None
    for line in text.splitlines(keepends=True):
        raw = line.rstrip("\n\r")
        m_begin = BEGIN.match(raw)
        m_end = END.match(raw)
        if skipping is None and m_begin:
            name = m_begin.group(1)
            if name not in enabled:
                skipping = name
            # drop marker lines either way
            continue
        if skipping is not None:
            if m_end and m_end.group(1) == skipping:
                skipping = None
            continue
        if m_end:
            # stray end marker
            continue
        out.append(line if line.endswith("\n") else line + "\n")
    if skipping is not None:
        raise SystemExit(f"ERROR: unclosed @module {skipping} in nginx conf")
    header = (
        "# GENERATED by deploy/gateway/render-runtime-nginx.py — do not edit by hand.\n"
        f"# enabled modules: {', '.join(sorted(enabled))}\n"
    )
    return header + "".join(out)


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit(
            "Usage: render-runtime-nginx.py <runtime-modules.json> <full.conf> <out.conf>"
        )
    modules_path = Path(sys.argv[1])
    src = Path(sys.argv[2])
    dst = Path(sys.argv[3])
    enabled = enabled_set(modules_path)
    if "web" not in enabled:
        raise SystemExit("ERROR: web must be enabled")
    text = src.read_text(encoding="utf-8")
    rendered = filter_conf(text, enabled)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(rendered, encoding="utf-8")
    print(f"rendered nginx → {dst} (enabled={','.join(sorted(enabled))})")


if __name__ == "__main__":
    main()
