/** @deprecated 请改引 `sa2kit/business/calendar/ui/web` / domain */
export type {
  CalendarEvent,
  RecurrenceRule,
  Reminder,
  CalendarConfig,
  EventFormData,
  RecurrenceFormData,
  ReminderFormData,
  CreateEventRequest,
  UpdateEventRequest,
  DeleteEventRequest,
  GetEventsRequest,
  ApiResponse,
  EventsResponse,
  EventResponse,
  CalendarViewProps,
  EventCardProps,
  EventFormProps,
  EventModalProps,
  MiniCalendarProps,
  EventListProps,
  CalendarState,
  CalendarActions,
  UseCalendarReturn,
  UseEventsReturn,
  DateRange,
  CalendarCell,
  TimeSlot,
  EventListSort,
  EventListFilter,
  EventListConfig,
  CalendarService,
  CalendarDbService,
} from 'sa2kit/business/calendar/ui/web';
export {
  RecurrenceType,
  ReminderType,
  ReminderStatus,
  CalendarViewType,
  EventColor,
  EventPriority,
  EventSortField,
  SortDirection,
  EventListDisplayMode,
} from 'sa2kit/business/calendar/ui/web';
